name: Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci
        working-directory: backend
      - run: npm run lint
        working-directory: backend
    name: Backend Check
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci
        working-directory: frontend
      - run: npm run lint
        working-directory: frontend
    name: Frontend Check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cp .env.example .env
      - run: docker compose up --build -d --wait # Compose and wait for all to be up 
      - run: ./scripts/smoke-test.sh
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v7

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to ghcr
        uses: docker/login-action
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
            ghcr.io/ivandjuka77/link-shortener-backend:${{ github.sha }}
            ghcr.io/ivandjuka77/link-shortener-backend:latest
          context: backend
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend

      - name: Build frontend image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
            ghcr.io/ivandjuka77/link-shortener-frontend:${{ github.sha }}
            ghcr.io/ivandjuka77/link-shortener-frontend:latest
          context: frontend
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend